SET WATCOM=C:
SET PATH=%WATCOM%\BINW;%WATCOM%\BINW\DOS;%PATH%
SET INCLUDE=%WATCOM%\H;%WATCOM%\H\NT;%WATCOM%\H\NT\DIRECTX;%WATCOM%\H\NT\DDK
SET LIB=%WATCOM%\LIB386
SET DOS4G=QUIET
SET WWFLAT=D:\WWFLAT32
SET PATH=%PATH%;D:\CODE\UTILS
